create table public.airlines (
  id uuid not null default gen_random_uuid (),
  name text not null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  logo_url text null,
  constraint airlines_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_airlines_name on public.airlines using btree (name) TABLESPACE pg_default;

create table public.airline_codes (
  id uuid not null default gen_random_uuid (),
  airline_id uuid not null,
  iata_code character(2) null,
  icao_code character(3) null,
  is_primary boolean null default false,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  constraint airline_codes_pkey primary key (id),
  constraint airline_codes_airline_id_fkey foreign KEY (airline_id) references airlines (id) on delete CASCADE
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_airline_codes_iata on public.airline_codes using btree (iata_code) TABLESPACE pg_default
where
  (iata_code is not null);

create unique INDEX IF not exists uq_airline_codes_icao on public.airline_codes using btree (icao_code) TABLESPACE pg_default
where
  (icao_code is not null);

create index IF not exists idx_airline_codes_airline_id on public.airline_codes using btree (airline_id) TABLESPACE pg_default;

create index IF not exists idx_airline_codes_iata_code on public.airline_codes using btree (iata_code) TABLESPACE pg_default;

create index IF not exists idx_airline_codes_icao_code on public.airline_codes using btree (icao_code) TABLESPACE pg_default;

create index IF not exists idx_airline_codes_is_primary on public.airline_codes using btree (is_primary) TABLESPACE pg_default;

create table public.airports (
  id uuid not null default gen_random_uuid (),
  name text not null,
  iata_code character(3) not null,
  icao_code character(4) null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  country text null,
  city text null,
  constraint airports_pkey primary key (id),
  constraint airports_iata_code_key unique (iata_code),
  constraint airports_icao_code_key unique (icao_code)
) TABLESPACE pg_default;

create index IF not exists idx_airports_iata_code on public.airports using btree (iata_code) TABLESPACE pg_default;

create index IF not exists idx_airports_icao_code on public.airports using btree (icao_code) TABLESPACE pg_default;

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_type text NOT NULL CHECK (actor_type = ANY (ARRAY['customer'::text, 'admin'::text, 'system'::text, 'webhook'::text])),
  actor_id uuid,
  action text NOT NULL,
  resource_type text,
  resource_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.booking_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  activity_type text NOT NULL,
  activity_description text,
  performed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  version_id uuid,
  amendment_id uuid,
  change_category character varying,
  change_impact character varying CHECK (change_impact::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  automated boolean DEFAULT false,
  metadata jsonb,
  description text,
  CONSTRAINT booking_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT booking_activity_log_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_activity_log_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.booking_versions(id)
);
CREATE TABLE public.booking_amendments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  version_id uuid,
  amendment_type character varying NOT NULL CHECK (amendment_type::text = ANY (ARRAY['minor'::character varying, 'major'::character varying, 'critical'::character varying]::text[])),
  amendment_category character varying NOT NULL,
  amendment_reason text NOT NULL,
  amendment_description text,
  requires_approval boolean DEFAULT false,
  approval_workflow character varying DEFAULT 'none'::character varying CHECK (approval_workflow::text = ANY (ARRAY['none'::character varying, 'consultant'::character varying, 'manager'::character varying, 'finance'::character varying, 'client'::character varying]::text[])),
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'auto_approved'::character varying]::text[])),
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  financial_impact numeric DEFAULT 0,
  impact_currency character varying DEFAULT 'GBP'::character varying,
  impact_description text,
  notify_client boolean DEFAULT false,
  client_notification_sent boolean DEFAULT false,
  client_notification_sent_at timestamp with time zone,
  client_response_received boolean DEFAULT false,
  client_response_received_at timestamp with time zone,
  client_response text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'cancelled'::character varying, 'superseded'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_amendments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_amendments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_amendments_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.booking_versions(id),
  CONSTRAINT booking_amendments_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id),
  CONSTRAINT booking_amendments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT booking_amendments_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES auth.users(id)
);
CREATE TABLE public.booking_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  component_type text NOT NULL CHECK (component_type = ANY (ARRAY['ticket'::text, 'hotel_room'::text, 'circuit_transfer'::text, 'airport_transfer'::text, 'flight'::text, 'extra'::text])),
  component_id uuid,
  component_name text,
  quantity integer,
  unit_price numeric,
  total_price numeric,
  component_data jsonb,
  component_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT booking_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['deposit'::text, 'second_payment'::text, 'third_payment'::text, 'final_payment'::text, 'additional'::text, 'refund'::text])),
  payment_number integer NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'GBP'::text,
  due_date date,
  paid boolean NOT NULL DEFAULT false,
  paid_at timestamp with time zone,
  payment_reference text,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  xero_invoice_id text,
  xero_invoice_number text,
  xero_synced_at timestamp with time zone,
  xero_sync_status text DEFAULT 'pending'::text CHECK (xero_sync_status = ANY (ARRAY['pending'::text, 'pending_edit'::text, 'synced'::text, 'failed'::text, 'ignored'::text])),
  xero_last_synced_amount numeric,
  xero_last_synced_due_date date,
  xero_last_synced_description text,
  xero_tracking_overrides jsonb,
  CONSTRAINT booking_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_sequences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  event_code text NOT NULL,
  year integer NOT NULL,
  current_sequence integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_sequences_pkey PRIMARY KEY (id),
  CONSTRAINT booking_sequences_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.booking_travelers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  traveler_type text NOT NULL CHECK (traveler_type = ANY (ARRAY['lead'::text, 'guest'::text])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone text,
  date_of_birth date,
  passport_number text,
  nationality text,
  dietary_restrictions text,
  accessibility_needs text,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postal_code text,
  country text,
  CONSTRAINT booking_travelers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_travelers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  version_number integer NOT NULL,
  version_type character varying NOT NULL DEFAULT 'amendment'::character varying CHECK (version_type::text = ANY (ARRAY['initial'::character varying, 'amendment'::character varying, 'rollback'::character varying, 'actualisation'::character varying]::text[])),
  version_reason text,
  version_description text,
  amendment_type character varying,
  amendment_category character varying,
  requires_approval boolean DEFAULT false,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'auto_approved'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  changes_summary jsonb,
  change_count integer DEFAULT 0,
  booking_snapshot jsonb NOT NULL,
  travelers_snapshot jsonb,
  components_snapshot jsonb,
  flights_snapshot jsonb,
  payments_snapshot jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_versions_pkey PRIMARY KEY (id),
  CONSTRAINT booking_versions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT booking_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_reference text NOT NULL UNIQUE,
  quote_id uuid,
  parent_quote_id uuid,
  quote_version integer,
  event_id uuid,
  client_id uuid,
  consultant_id uuid,
  user_id uuid,
  team_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'provisional'::text, 'pending_payment'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'refunded'::text])),
  total_price numeric NOT NULL,
  currency text DEFAULT 'GBP'::text,
  payment_schedule_snapshot jsonb,
  package_snapshot jsonb,
  provisional_expires_at timestamp with time zone,
  provisional_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  lead_traveler_id uuid,
  booking_type character varying NOT NULL DEFAULT 'actual'::character varying,
  protection_scheme text NOT NULL DEFAULT 'none'::text CHECK (protection_scheme = ANY (ARRAY['ATOL'::text, 'ABTOT'::text, 'none'::text])),
  booking_notes text,
  internal_notes text,
  special_requests text,
  package_type text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'partial_refund'::text, 'refunded'::text])),
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  acquisition_source_id uuid,
  commission_payable boolean DEFAULT false,
  commission_amount numeric DEFAULT 0,
  commission_paid boolean DEFAULT false,
  exchange_rate numeric DEFAULT 1.000000,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_lead_traveler_id_fkey FOREIGN KEY (lead_traveler_id) REFERENCES public.booking_travelers(id),
  CONSTRAINT bookings_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT bookings_parent_quote_id_fkey FOREIGN KEY (parent_quote_id) REFERENCES public.quotes(id),
  CONSTRAINT bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT bookings_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.team_members(id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bookings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT bookings_acquisition_source_id_fkey FOREIGN KEY (acquisition_source_id) REFERENCES public.acquisition_sources(id)
);

CREATE TABLE public.bookings_flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  source_flight_id uuid,
  api_source text,
  ticketing_deadline date,
  booking_pnr text,
  flight_status text CHECK (flight_status = ANY (ARRAY['Booked - Ticketed - Paid'::text, 'Booked - Ticketed - Not Paid'::text, 'Booked - Not Ticketed'::text])),
  flight_details jsonb,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric,
  total_price numeric,
  currency text DEFAULT 'GBP'::text,
  refundable boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  flight_type text NOT NULL DEFAULT 'booked'::text CHECK (flight_type = ANY (ARRAY['booked'::text, 'customer'::text])),
  cost numeric DEFAULT 0,
  outbound_airline_code text,
  inbound_airline_code text,
  CONSTRAINT bookings_flights_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_flights_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT bookings_flights_source_flight_id_fkey FOREIGN KEY (source_flight_id) REFERENCES public.flights(id)
);

CREATE TABLE public.client_interactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  user_id uuid NOT NULL,
  interaction_type text NOT NULL CHECK (interaction_type = ANY (ARRAY['email'::text, 'phone'::text, 'meeting'::text, 'quote_sent'::text, 'quote_accepted'::text, 'quote_declined'::text, 'follow_up'::text, 'note'::text])),
  subject text,
  content text,
  outcome text,
  next_action text,
  scheduled_follow_up timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.client_travel_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  quote_id uuid,
  destination text NOT NULL,
  start_date date,
  end_date date,
  trip_type text,
  total_spent numeric,
  currency text DEFAULT 'USD'::text,
  status text DEFAULT 'completed'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now()
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text UNIQUE,
  phone text,
  company text,
  job_title text,
  date_of_birth date,
  passport_number text,
  nationality text,
  preferred_language text DEFAULT 'English'::text,
  address jsonb,
  preferences jsonb,
  notes text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'prospect'::text, 'vip'::text])),
  source text,
  tags ARRAY DEFAULT '{}'::text[],
  budget_preference jsonb,
  payment_preference text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_contact_at timestamp with time zone,
  search_vector tsvector,
  hubspot_contact_id text,
  acquisition text,
  original_source text,
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  points_balance integer NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
  lifetime_points_earned integer NOT NULL DEFAULT 0,
  lifetime_points_spent integer NOT NULL DEFAULT 0,
  loyalty_enrolled boolean,
  loyalty_enrolled_at timestamp with time zone,
  loyalty_signup_source text CHECK (loyalty_signup_source = ANY (ARRAY['referral'::text, 'auto_enrolled'::text, 'self_signup'::text])),
  first_loyalty_booking_at timestamp with time zone,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.event_consultants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  consultant_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  notes text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'completed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_consultants_pkey PRIMARY KEY (id),
  CONSTRAINT event_consultants_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_consultants_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.team_members(id),
  CONSTRAINT event_consultants_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sport_id uuid,
  name text NOT NULL,
  location text,
  start_date date,
  end_date date,
  venue_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  event_image jsonb,
  primary_consultant_id uuid,
  is_provisional boolean NOT NULL DEFAULT true,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  active boolean,
  hide_b2b boolean DEFAULT false,
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES public.sports(id),
  CONSTRAINT events_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id),
  CONSTRAINT events_primary_consultant_id_fkey FOREIGN KEY (primary_consultant_id) REFERENCES public.team_members(id)
);


CREATE TABLE public.loyalty_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  points_per_pound numeric NOT NULL DEFAULT 0.05,
  currency text NOT NULL DEFAULT 'GBP'::text,
  referral_bonus_referee integer NOT NULL DEFAULT 100,
  referral_bonus_referrer integer NOT NULL DEFAULT 100,
  referral_link_expiry_days integer DEFAULT 90,
  min_redemption_points integer NOT NULL DEFAULT 100,
  redemption_increment integer NOT NULL DEFAULT 100,
  point_value numeric NOT NULL DEFAULT 1.00,
  points_expire_after_days integer,
  referral_program_enabled boolean DEFAULT true,
  redemption_enabled boolean DEFAULT true,
  portal_name text DEFAULT 'Customer Portal'::text,
  primary_color text DEFAULT '#000000'::text,
  logo_url text,
  terms_and_conditions_url text,
  help_email text,
  settings_metadata jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['earn'::text, 'spend'::text, 'adjustment'::text, 'expired'::text, 'refund'::text])),
  points integer NOT NULL,
  balance_after integer NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['purchase'::text, 'referral_signup'::text, 'referral_booking'::text, 'redemption'::text, 'refund'::text, 'manual_adjustment'::text, 'expiry'::text])),
  source_reference_id text,
  purchase_amount numeric,
  purchase_currency text DEFAULT 'GBP'::text,
  description text NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);

CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['points_earned'::text, 'points_spent'::text, 'referral_signup'::text, 'referral_completed'::text, 'booking_confirmed'::text, 'booking_cancelled'::text, 'system'::text, 'promotion'::text])),
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  action_label text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.package_components (
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tier_id uuid NOT NULL,
  event_id uuid NOT NULL,
  component_type text NOT NULL CHECK (component_type = ANY (ARRAY['ticket'::text, 'hotel_room'::text, 'circuit_transfer'::text, 'airport_transfer'::text, 'flight'::text, 'extra'::text])),
  component_id uuid NOT NULL,
  default_quantity integer DEFAULT 1,
  price_override numeric,
  notes text,
  CONSTRAINT package_components_pkey PRIMARY KEY (id),
  CONSTRAINT package_components_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.package_tiers(id),
  CONSTRAINT package_components_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.package_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid,
  name text NOT NULL,
  description text,
  price_override numeric,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  short_label text,
  display_order integer,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  CONSTRAINT package_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT package_tiers_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  base_type text CHECK (base_type = ANY (ARRAY['Grandstand'::text, 'VIP'::text])),
  active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  package_image jsonb,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT packages_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);

CREATE TABLE public.redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  points_redeemed integer NOT NULL CHECK (points_redeemed > 0),
  discount_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'GBP'::text,
  quote_id uuid,
  booking_id uuid,
  booking_reference text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'applied'::text, 'cancelled'::text, 'refunded'::text])),
  transaction_id uuid,
  reserved_at timestamp with time zone DEFAULT now(),
  applied_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  refunded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT redemptions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT redemptions_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT redemptions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT redemptions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.loyalty_transactions(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_client_id uuid NOT NULL,
  referee_email text NOT NULL,
  referee_client_id uuid,
  referral_code text NOT NULL UNIQUE,
  referral_link text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'signed_up'::text, 'completed'::text, 'expired'::text, 'cancelled'::text])),
  referee_signup_points integer DEFAULT 0,
  referrer_booking_points integer DEFAULT 0,
  referee_signup_transaction_id uuid,
  referrer_booking_transaction_id uuid,
  first_booking_id uuid,
  first_booking_reference text,
  signed_up_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_client_id_fkey FOREIGN KEY (referrer_client_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_referee_client_id_fkey FOREIGN KEY (referee_client_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_referee_signup_transaction_id_fkey FOREIGN KEY (referee_signup_transaction_id) REFERENCES public.loyalty_transactions(id),
  CONSTRAINT referrals_referrer_booking_transaction_id_fkey FOREIGN KEY (referrer_booking_transaction_id) REFERENCES public.loyalty_transactions(id)
);

CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  name text,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'sales'::text, 'operations'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'invited'::text, 'inactive'::text])),
  invited_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invited_by uuid,
  invitation_token text,
  invitation_expires_at timestamp with time zone,
  team_id uuid,
  phone text,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT team_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_id uuid NOT NULL,
  max_members integer DEFAULT 10000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  logo_url text,
  agency_name text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
create table public.venues (
  id uuid not null default gen_random_uuid (),
  name text not null,
  slug text null,
  country text null,
  city text null,
  timezone text null,
  latitude numeric(9, 6) null,
  longitude numeric(9, 6) null,
  description text null,
  images jsonb null,
  website text null,
  created_at timestamp without time zone null default now(),
  updated_at timestamp without time zone null default now(),
  map_img jsonb null,
  constraint venues_pkey primary key (id),
  constraint venues_slug_key unique (slug)
) TABLESPACE pg_default;