-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
CREATE TABLE public.airline_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  airline_id uuid NOT NULL,
  iata_code character,
  icao_code character,
  is_primary boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT airline_codes_pkey PRIMARY KEY (id),
  CONSTRAINT airline_codes_airline_id_fkey FOREIGN KEY (airline_id) REFERENCES public.airlines(id)
);
CREATE TABLE public.airlines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  logo_url text,
  CONSTRAINT airlines_pkey PRIMARY KEY (id)
);
CREATE TABLE public.airport_transfers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  hotel_id uuid,
  transport_type text NOT NULL,
  max_capacity integer NOT NULL,
  used integer DEFAULT 0,
  supplier text,
  quote_currency text DEFAULT 'GBP'::text,
  supplier_quote_per_car_local numeric,
  supplier_quote_per_car_gbp numeric,
  paid_to_supplier boolean DEFAULT false,
  outstanding boolean DEFAULT true,
  markup numeric DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  price_per_car_gbp_markup numeric DEFAULT (supplier_quote_per_car_gbp + ((supplier_quote_per_car_gbp * COALESCE(markup, (0)::numeric)) / (100)::numeric)),
  active boolean DEFAULT true,
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT airport_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT airport_transfers_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT airport_transfers_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.gpgt_hotels(id),
  CONSTRAINT airport_transfers_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.airports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  iata_code character NOT NULL UNIQUE,
  icao_code character UNIQUE,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  country text,
  city text,
  CONSTRAINT airports_pkey PRIMARY KEY (id)
);

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_type text NOT NULL CHECK (actor_type = ANY (ARRAY['customer'::text, 'admin'::text, 'system'::text, 'webhook'::text])),
  actor_id uuid,
  action text NOT NULL,
  resource_type text,
  resource_id uuid,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.booking_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  activity_type text NOT NULL,
  activity_description text,
  performed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  version_id uuid,
  amendment_id uuid,
  change_category character varying,
  change_impact character varying CHECK (change_impact::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  automated boolean DEFAULT false,
  metadata jsonb,
  description text,
  CONSTRAINT booking_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT booking_activity_log_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_activity_log_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.booking_versions(id)
);
CREATE TABLE public.booking_amendments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  version_id uuid,
  amendment_type character varying NOT NULL CHECK (amendment_type::text = ANY (ARRAY['minor'::character varying, 'major'::character varying, 'critical'::character varying]::text[])),
  amendment_category character varying NOT NULL,
  amendment_reason text NOT NULL,
  amendment_description text,
  requires_approval boolean DEFAULT false,
  approval_workflow character varying DEFAULT 'none'::character varying CHECK (approval_workflow::text = ANY (ARRAY['none'::character varying, 'consultant'::character varying, 'manager'::character varying, 'finance'::character varying, 'client'::character varying]::text[])),
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'auto_approved'::character varying]::text[])),
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  rejected_by uuid,
  rejected_at timestamp with time zone,
  rejection_reason text,
  financial_impact numeric DEFAULT 0,
  impact_currency character varying DEFAULT 'GBP'::character varying,
  impact_description text,
  notify_client boolean DEFAULT false,
  client_notification_sent boolean DEFAULT false,
  client_notification_sent_at timestamp with time zone,
  client_response_received boolean DEFAULT false,
  client_response_received_at timestamp with time zone,
  client_response text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'cancelled'::character varying, 'superseded'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_amendments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_amendments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_amendments_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.booking_versions(id),
  CONSTRAINT booking_amendments_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id),
  CONSTRAINT booking_amendments_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT booking_amendments_rejected_by_fkey FOREIGN KEY (rejected_by) REFERENCES auth.users(id)
);
CREATE TABLE public.booking_components (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  component_type text NOT NULL CHECK (component_type = ANY (ARRAY['ticket'::text, 'hotel_room'::text, 'circuit_transfer'::text, 'airport_transfer'::text, 'flight'::text, 'extra'::text])),
  component_id uuid,
  component_name text,
  quantity integer,
  unit_price numeric,
  total_price numeric,
  component_data jsonb,
  component_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT booking_components_pkey PRIMARY KEY (id),
  CONSTRAINT booking_components_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  payment_type text NOT NULL CHECK (payment_type = ANY (ARRAY['deposit'::text, 'second_payment'::text, 'third_payment'::text, 'final_payment'::text, 'additional'::text, 'refund'::text])),
  payment_number integer NOT NULL,
  amount numeric NOT NULL,
  currency text DEFAULT 'GBP'::text,
  due_date date,
  paid boolean NOT NULL DEFAULT false,
  paid_at timestamp with time zone,
  payment_reference text,
  payment_method text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  xero_invoice_id text,
  xero_invoice_number text,
  xero_synced_at timestamp with time zone,
  xero_sync_status text DEFAULT 'pending'::text CHECK (xero_sync_status = ANY (ARRAY['pending'::text, 'pending_edit'::text, 'synced'::text, 'failed'::text, 'ignored'::text])),
  xero_last_synced_amount numeric,
  xero_last_synced_due_date date,
  xero_last_synced_description text,
  xero_tracking_overrides jsonb,
  CONSTRAINT booking_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_sequences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  event_code text NOT NULL,
  year integer NOT NULL,
  current_sequence integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_sequences_pkey PRIMARY KEY (id),
  CONSTRAINT booking_sequences_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.booking_travelers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  traveler_type text NOT NULL CHECK (traveler_type = ANY (ARRAY['lead'::text, 'guest'::text])),
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text,
  phone text,
  date_of_birth date,
  passport_number text,
  nationality text,
  dietary_restrictions text,
  accessibility_needs text,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  postal_code text,
  country text,
  CONSTRAINT booking_travelers_pkey PRIMARY KEY (id),
  CONSTRAINT booking_travelers_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.booking_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  version_number integer NOT NULL,
  version_type character varying NOT NULL DEFAULT 'amendment'::character varying CHECK (version_type::text = ANY (ARRAY['initial'::character varying, 'amendment'::character varying, 'rollback'::character varying, 'actualisation'::character varying]::text[])),
  version_reason text,
  version_description text,
  amendment_type character varying,
  amendment_category character varying,
  requires_approval boolean DEFAULT false,
  approval_status character varying DEFAULT 'pending'::character varying CHECK (approval_status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'auto_approved'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  approval_notes text,
  changes_summary jsonb,
  change_count integer DEFAULT 0,
  booking_snapshot jsonb NOT NULL,
  travelers_snapshot jsonb,
  components_snapshot jsonb,
  flights_snapshot jsonb,
  payments_snapshot jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT booking_versions_pkey PRIMARY KEY (id),
  CONSTRAINT booking_versions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_versions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT booking_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_reference text NOT NULL UNIQUE,
  quote_id uuid,
  parent_quote_id uuid,
  quote_version integer,
  event_id uuid,
  client_id uuid,
  consultant_id uuid,
  user_id uuid,
  team_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'provisional'::text, 'pending_payment'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'refunded'::text])),
  total_price numeric NOT NULL,
  currency text DEFAULT 'GBP'::text,
  payment_schedule_snapshot jsonb,
  package_snapshot jsonb,
  provisional_expires_at timestamp with time zone,
  provisional_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  lead_traveler_id uuid,
  booking_type character varying NOT NULL DEFAULT 'actual'::character varying,
  protection_scheme text NOT NULL DEFAULT 'none'::text CHECK (protection_scheme = ANY (ARRAY['ATOL'::text, 'ABTOT'::text, 'none'::text])),
  booking_notes text,
  internal_notes text,
  special_requests text,
  package_type text,
  payment_status text DEFAULT 'pending'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'partial'::text, 'paid'::text, 'overdue'::text, 'partial_refund'::text, 'refunded'::text])),
  confirmed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  acquisition_source_id uuid,
  commission_payable boolean DEFAULT false,
  commission_amount numeric DEFAULT 0,
  commission_paid boolean DEFAULT false,
  exchange_rate numeric DEFAULT 1.000000,
  points_earned integer DEFAULT 0 CHECK (points_earned >= 0),
  points_used integer DEFAULT 0 CHECK (points_used >= 0),
  discount_applied numeric DEFAULT 0 CHECK (discount_applied >= 0::numeric),
  is_first_loyalty_booking boolean DEFAULT false,
  earn_transaction_id uuid,
  spend_transaction_id uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_lead_traveler_id_fkey FOREIGN KEY (lead_traveler_id) REFERENCES public.booking_travelers(id),
  CONSTRAINT bookings_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT bookings_parent_quote_id_fkey FOREIGN KEY (parent_quote_id) REFERENCES public.quotes(id),
  CONSTRAINT bookings_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT bookings_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT bookings_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.team_members(id),
  CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT bookings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT bookings_acquisition_source_id_fkey FOREIGN KEY (acquisition_source_id) REFERENCES public.acquisition_sources(id),
  CONSTRAINT bookings_earn_transaction_id_fkey FOREIGN KEY (earn_transaction_id) REFERENCES public.loyalty_transactions(id),
  CONSTRAINT bookings_spend_transaction_id_fkey FOREIGN KEY (spend_transaction_id) REFERENCES public.loyalty_transactions(id)
);
CREATE TABLE public.bookings_flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  source_flight_id uuid,
  api_source text,
  ticketing_deadline date,
  booking_pnr text,
  flight_status text CHECK (flight_status = ANY (ARRAY['Booked - Ticketed - Paid'::text, 'Booked - Ticketed - Not Paid'::text, 'Booked - Not Ticketed'::text])),
  flight_details jsonb,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric,
  total_price numeric,
  currency text DEFAULT 'GBP'::text,
  refundable boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deleted_at timestamp with time zone,
  flight_type text NOT NULL DEFAULT 'booked'::text CHECK (flight_type = ANY (ARRAY['booked'::text, 'customer'::text])),
  cost numeric DEFAULT 0,
  outbound_airline_code text,
  inbound_airline_code text,
  CONSTRAINT bookings_flights_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_flights_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT bookings_flights_source_flight_id_fkey FOREIGN KEY (source_flight_id) REFERENCES public.flights(id)
);
CREATE TABLE public.circuit_transfers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  hotel_id uuid,
  transfer_type text NOT NULL,
  used integer DEFAULT 0,
  coach_capacity integer NOT NULL,
  days integer NOT NULL,
  quote_hours integer,
  expected_hours integer,
  supplier text,
  coach_cost_per_day_local numeric,
  coach_cost_per_hour_local numeric,
  coach_extra_cost_per_hour_local numeric,
  coach_vat numeric,
  parking_ticket_per_coach_per_day numeric,
  supplier_currency text DEFAULT 'EUR'::text,
  guide_included boolean DEFAULT true,
  guide_cost_per_day numeric,
  guide_cost_per_hour_local numeric,
  guide_extra_cost_per_hour_local numeric,
  guide_vat numeric,
  markup_percent numeric DEFAULT 0.00,
  coaches_required integer DEFAULT ceil(((used)::numeric / (coach_capacity)::numeric)),
  coach_cost_local numeric,
  guide_cost_local numeric,
  utilisation_percent numeric DEFAULT 100,
  utilisation_cost_per_seat_local numeric,
  coach_cost_gbp numeric,
  guide_cost_gbp numeric,
  utilisation_cost_per_seat_gbp numeric,
  sell_price_per_seat_gbp numeric,
  active boolean DEFAULT true,
  notes text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  transfer_days text,
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT circuit_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT circuit_transfers_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT circuit_transfers_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT circuit_transfers_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.gpgt_hotels(id)
);

CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  team_id uuid,
  first_name text NOT NULL,
  last_name text NOT NULL,
  email text UNIQUE,
  phone text,
  company text,
  job_title text,
  date_of_birth date,
  passport_number text,
  nationality text,
  preferred_language text DEFAULT 'English'::text,
  address jsonb,
  preferences jsonb,
  notes text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'prospect'::text, 'vip'::text])),
  source text,
  tags ARRAY DEFAULT '{}'::text[],
  budget_preference jsonb,
  payment_preference text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_contact_at timestamp with time zone,
  search_vector tsvector,
  hubspot_contact_id text,
  acquisition text,
  original_source text,
  properties jsonb NOT NULL DEFAULT '{}'::jsonb,
  points_balance integer NOT NULL DEFAULT 0 CHECK (points_balance >= 0),
  lifetime_points_earned integer NOT NULL DEFAULT 0,
  lifetime_points_spent integer NOT NULL DEFAULT 0,
  loyalty_enrolled boolean,
  loyalty_enrolled_at timestamp with time zone,
  loyalty_signup_source text CHECK (loyalty_signup_source = ANY (ARRAY['referral'::text, 'auto_enrolled'::text, 'self_signup'::text])),
  first_loyalty_booking_at timestamp with time zone,
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT clients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.customer_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  ip_address inet,
  user_agent text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT customer_sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.event_consultants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  consultant_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  notes text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'completed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_consultants_pkey PRIMARY KEY (id),
  CONSTRAINT event_consultants_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_consultants_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.team_members(id),
  CONSTRAINT event_consultants_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES auth.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sport_id uuid,
  name text NOT NULL,
  location text,
  start_date date,
  end_date date,
  venue_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  event_image jsonb,
  primary_consultant_id uuid,
  is_provisional boolean NOT NULL DEFAULT true,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  active boolean,
  hide_b2b boolean DEFAULT false,
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_sport_id_fkey FOREIGN KEY (sport_id) REFERENCES public.sports(id),
  CONSTRAINT events_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id),
  CONSTRAINT events_primary_consultant_id_fkey FOREIGN KEY (primary_consultant_id) REFERENCES public.team_members(id)
);
CREATE TABLE public.extras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  event_id uuid NOT NULL,
  extra_type text NOT NULL CHECK (extra_type = ANY (ARRAY['lounge_pass'::text, 'meet_greet'::text, 'pit_lane_walk'::text, 'hospitality'::text, 'parking'::text, 'transport'::text, 'accommodation'::text, 'other'::text])),
  name text NOT NULL,
  description text,
  cost numeric NOT NULL CHECK (cost >= 0::numeric),
  markup numeric NOT NULL CHECK (markup >= 0::numeric),
  currency text DEFAULT 'GBP'::text,
  is_active boolean DEFAULT true,
  notes text,
  max_quantity integer,
  quantity_used integer DEFAULT 0 CHECK (quantity_used >= 0),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  sell_price numeric DEFAULT round((cost * ((1)::numeric + (markup / (100)::numeric))), 2),
  CONSTRAINT extras_pkey PRIMARY KEY (id),
  CONSTRAINT extras_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT extras_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);

CREATE TABLE public.flights (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  outbound_flight_number text NOT NULL,
  outbound_departure_airport_code text NOT NULL,
  outbound_departure_airport_name text NOT NULL,
  outbound_arrival_airport_code text NOT NULL,
  outbound_arrival_airport_name text NOT NULL,
  outbound_departure_datetime timestamp without time zone NOT NULL,
  outbound_arrival_datetime timestamp without time zone NOT NULL,
  inbound_flight_number text,
  inbound_departure_airport_code text,
  inbound_departure_airport_name text,
  inbound_arrival_airport_code text,
  inbound_arrival_airport_name text,
  inbound_departure_datetime timestamp without time zone,
  inbound_arrival_datetime timestamp without time zone,
  airline text,
  cabin text,
  total_price_gbp numeric NOT NULL,
  currency text DEFAULT 'GBP'::text,
  refundable boolean DEFAULT false,
  baggage_allowance text,
  notes text,
  supplier text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  active boolean DEFAULT true,
  airline_code text,
  outbound_airline_code text,
  inbound_airline_code text,
  CONSTRAINT flights_pkey PRIMARY KEY (id),
  CONSTRAINT flights_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.gpgt_hotels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  brand text,
  star_rating integer,
  address text,
  city text,
  country text,
  latitude numeric,
  longitude numeric,
  description text,
  images jsonb,
  amenities jsonb,
  check_in_time time without time zone,
  check_out_time time without time zone,
  contact_email text,
  phone text,
  room_types jsonb,
  created_at timestamp without time zone DEFAULT now(),
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT gpgt_hotels_pkey PRIMARY KEY (id),
  CONSTRAINT gpgt_hotels_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);

CREATE TABLE public.hotel_rooms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hotel_id uuid NOT NULL,
  room_type_id text NOT NULL,
  event_id uuid,
  check_in date NOT NULL,
  check_out date NOT NULL,
  quantity_total integer NOT NULL,
  quantity_reserved integer DEFAULT 0,
  supplier_price_per_night numeric,
  supplier_currency text DEFAULT 'EUR'::text,
  markup_percent numeric DEFAULT 0.00,
  vat_percentage numeric,
  resort_fee numeric,
  resort_fee_type text DEFAULT 'per_night'::text,
  city_tax numeric,
  city_tax_type text DEFAULT 'per_person_per_night'::text,
  extra_night_markup_percent numeric,
  contracted boolean DEFAULT false,
  attrition_deadline date,
  release_allowed_percent numeric,
  penalty_terms text,
  supplier text,
  supplier_ref text,
  contract_file_path text,
  active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  max_people integer,
  total_supplier_price_per_night numeric,
  total_price_per_night_gbp numeric,
  total_price_per_stay_gbp numeric,
  total_price_per_night_gbp_with_markup numeric DEFAULT (total_price_per_night_gbp + ((total_price_per_night_gbp * markup_percent) / (100)::numeric)),
  total_price_per_stay_gbp_with_markup numeric DEFAULT (total_price_per_stay_gbp + ((total_price_per_stay_gbp * markup_percent) / (100)::numeric)),
  is_provisional boolean NOT NULL DEFAULT false,
  quantity_available integer DEFAULT 
CASE
    WHEN is_provisional THEN 0
    ELSE (quantity_total - quantity_reserved)
END,
  bed_type text DEFAULT 'Double Room'::text,
  commission_percent numeric DEFAULT 0.00 CHECK (commission_percent >= 0::numeric),
  flexibility text NOT NULL DEFAULT 'Flex'::text CHECK (flexibility = ANY (ARRAY['Flex'::text, 'Non Flex'::text])),
  board_type text NOT NULL DEFAULT 'Bed & Breakfast'::text CHECK (board_type = ANY (ARRAY['Room Only'::text, 'Bed & Breakfast'::text, 'Half Board'::text, 'Full Board'::text, 'All Inclusive'::text])),
  board_price_per_person_per_night numeric,
  extra_night_cost numeric,
  contract_id uuid,
  extra_night_price_gbp numeric DEFAULT (extra_night_cost * ((1)::numeric + (extra_night_markup_percent / (100)::numeric))),
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT hotel_rooms_pkey PRIMARY KEY (id),
  CONSTRAINT hotel_rooms_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT hotel_rooms_hotel_id_fkey FOREIGN KEY (hotel_id) REFERENCES public.gpgt_hotels(id),
  CONSTRAINT hotel_rooms_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT hotel_rooms_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.hotel_contracts(id)
);

CREATE TABLE public.loyalty_settings (
  id integer NOT NULL DEFAULT 1 CHECK (id = 1),
  points_per_pound numeric NOT NULL DEFAULT 0.05,
  currency text NOT NULL DEFAULT 'GBP'::text,
  referral_bonus_referee integer NOT NULL DEFAULT 100,
  referral_bonus_referrer integer NOT NULL DEFAULT 100,
  referral_link_expiry_days integer DEFAULT 90,
  min_redemption_points integer NOT NULL DEFAULT 100,
  redemption_increment integer NOT NULL DEFAULT 100,
  point_value numeric NOT NULL DEFAULT 1.00,
  points_expire_after_days integer,
  referral_program_enabled boolean DEFAULT true,
  redemption_enabled boolean DEFAULT true,
  portal_name text DEFAULT 'Customer Portal'::text,
  primary_color text DEFAULT '#000000'::text,
  logo_url text,
  terms_and_conditions_url text,
  help_email text,
  settings_metadata jsonb DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  transaction_type text NOT NULL CHECK (transaction_type = ANY (ARRAY['earn'::text, 'spend'::text, 'adjustment'::text, 'expired'::text, 'refund'::text])),
  points integer NOT NULL,
  balance_after integer NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['purchase'::text, 'referral_signup'::text, 'referral_booking'::text, 'redemption'::text, 'refund'::text, 'manual_adjustment'::text, 'expiry'::text])),
  source_reference_id text,
  purchase_amount numeric,
  purchase_currency text DEFAULT 'GBP'::text,
  description text NOT NULL,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);


CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['points_earned'::text, 'points_spent'::text, 'referral_signup'::text, 'referral_completed'::text, 'booking_confirmed'::text, 'booking_cancelled'::text, 'system'::text, 'promotion'::text])),
  read boolean DEFAULT false,
  read_at timestamp with time zone,
  action_url text,
  action_label text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.package_components (
  id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  tier_id uuid NOT NULL,
  event_id uuid NOT NULL,
  component_type text NOT NULL CHECK (component_type = ANY (ARRAY['ticket'::text, 'hotel_room'::text, 'circuit_transfer'::text, 'airport_transfer'::text, 'flight'::text, 'extra'::text])),
  component_id uuid NOT NULL,
  default_quantity integer DEFAULT 1,
  price_override numeric,
  notes text,
  CONSTRAINT package_components_pkey PRIMARY KEY (id),
  CONSTRAINT package_components_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.package_tiers(id),
  CONSTRAINT package_components_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id)
);
CREATE TABLE public.package_tiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_id uuid,
  name text NOT NULL,
  description text,
  price_override numeric,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  short_label text,
  display_order integer,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  CONSTRAINT package_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT package_tiers_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid,
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  base_type text CHECK (base_type = ANY (ARRAY['Grandstand'::text, 'VIP'::text])),
  active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  package_image jsonb,
  status text DEFAULT 'Coming Soon'::text CHECK (status = ANY (ARRAY['Sales Open'::text, 'Sales Closed'::text, 'Coming Soon'::text])),
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT packages_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.quotes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  client_id uuid,
  team_id uuid,
  consultant_id uuid,
  client_name text NOT NULL,
  client_email text,
  client_phone text,
  client_address jsonb,
  event_id uuid,
  event_name character varying,
  event_location character varying,
  event_start_date date,
  event_end_date date,
  package_id uuid,
  package_name character varying,
  package_base_type character varying,
  tier_id uuid,
  tier_name character varying,
  tier_description text,
  tier_price_override numeric,
  travelers jsonb NOT NULL,
  travelers_adults integer DEFAULT 1,
  travelers_children integer DEFAULT 0,
  travelers_total integer DEFAULT 1,
  total_price numeric,
  currency text DEFAULT 'GBP'::text CHECK (currency = ANY (ARRAY['GBP'::text, 'USD'::text, 'EUR'::text, 'CAD'::text, 'AUD'::text, 'AED'::text, 'BHD'::text, 'SGD'::text, 'NZD'::text, 'ZAR'::text, 'MYR'::text, 'QAR'::text, 'SAR'::text, 'INR'::text])),
  base_cost numeric,
  payment_deposit numeric DEFAULT 0,
  payment_second_payment numeric DEFAULT 0,
  payment_final_payment numeric DEFAULT 0,
  payment_deposit_date date,
  payment_second_payment_date date,
  payment_final_payment_date date,
  quote_number character varying UNIQUE,
  quote_reference character varying,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'declined'::text, 'expired'::text, 'confirmed'::text, 'cancelled'::text])),
  version integer DEFAULT 1,
  is_revision boolean DEFAULT false,
  parent_quote_id uuid,
  selected_components jsonb,
  selected_package jsonb,
  selected_tier jsonb,
  price_breakdown jsonb,
  internal_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  sent_at timestamp with time zone,
  accepted_at timestamp with time zone,
  declined_at timestamp with time zone,
  expired_at timestamp with time zone,
  payment_third_payment numeric DEFAULT 0,
  payment_third_payment_date date,
  alternative_totals jsonb,
  source text,
  event_status text NOT NULL DEFAULT 'actual'::text CHECK (event_status = ANY (ARRAY['provisional'::text, 'actual'::text])),
  exchange_rate numeric DEFAULT 1.000000,
  CONSTRAINT quotes_pkey PRIMARY KEY (id),
  CONSTRAINT quotes_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT quotes_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT quotes_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT quotes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT quotes_tier_id_fkey FOREIGN KEY (tier_id) REFERENCES public.package_tiers(id),
  CONSTRAINT quotes_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT quotes_consultant_id_fkey FOREIGN KEY (consultant_id) REFERENCES public.team_members(id),
  CONSTRAINT quotes_parent_quote_id_fkey FOREIGN KEY (parent_quote_id) REFERENCES public.quotes(id)
);
CREATE TABLE public.redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  points_redeemed integer NOT NULL CHECK (points_redeemed > 0),
  discount_amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'GBP'::text,
  quote_id uuid,
  booking_id uuid,
  booking_reference text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'applied'::text, 'cancelled'::text, 'refunded'::text])),
  transaction_id uuid,
  reserved_at timestamp with time zone DEFAULT now(),
  applied_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  refunded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT redemptions_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT redemptions_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES public.quotes(id),
  CONSTRAINT redemptions_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT redemptions_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.loyalty_transactions(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  referrer_client_id uuid NOT NULL,
  referee_email text NOT NULL,
  referee_client_id uuid,
  referral_code text NOT NULL UNIQUE,
  referral_link text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'signed_up'::text, 'completed'::text, 'expired'::text, 'cancelled'::text])),
  referee_signup_points integer DEFAULT 0,
  referrer_booking_points integer DEFAULT 0,
  referee_signup_transaction_id uuid,
  referrer_booking_transaction_id uuid,
  first_booking_id uuid,
  first_booking_reference text,
  signed_up_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_referrer_client_id_fkey FOREIGN KEY (referrer_client_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_referee_client_id_fkey FOREIGN KEY (referee_client_id) REFERENCES public.clients(id),
  CONSTRAINT referrals_referee_signup_transaction_id_fkey FOREIGN KEY (referee_signup_transaction_id) REFERENCES public.loyalty_transactions(id),
  CONSTRAINT referrals_referrer_booking_transaction_id_fkey FOREIGN KEY (referrer_booking_transaction_id) REFERENCES public.loyalty_transactions(id)
);

CREATE TABLE public.sports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  CONSTRAINT sports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  email text NOT NULL,
  name text,
  role text DEFAULT 'member'::text CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text, 'sales'::text, 'operations'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'invited'::text, 'inactive'::text])),
  invited_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  invited_by uuid,
  invitation_token text,
  invitation_expires_at timestamp with time zone,
  team_id uuid,
  phone text,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT team_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner_id uuid NOT NULL,
  max_members integer DEFAULT 10000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  logo_url text,
  agency_name text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ticket_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_name text NOT NULL,
  venue_id text,
  sport_type text,
  category_type text,
  description jsonb,
  options jsonb,
  ticket_delivery_days integer,
  media_files jsonb,
  created_at timestamp without time zone DEFAULT now(),
  features ARRAY DEFAULT '{}'::text[] CHECK (array_length(features, 1) <= 6),
  CONSTRAINT ticket_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  ticket_category_id uuid,
  quantity_total integer NOT NULL CHECK (quantity_total >= 0),
  quantity_reserved integer NOT NULL DEFAULT 0 CHECK (quantity_reserved >= 0),
  price numeric NOT NULL CHECK (price >= 0::numeric),
  markup_percent numeric DEFAULT 0.00 CHECK (markup_percent >= 0::numeric),
  price_with_markup numeric DEFAULT (price + ((price * markup_percent) / (100)::numeric)),
  currency text NOT NULL DEFAULT 'EUR'::text,
  ticket_type text,
  refundable boolean DEFAULT false,
  resellable boolean DEFAULT false,
  supplier text,
  supplier_ref text,
  ordered boolean DEFAULT false,
  ordered_at timestamp without time zone,
  paid boolean DEFAULT false,
  paid_at timestamp without time zone,
  tickets_received boolean DEFAULT false,
  tickets_received_at timestamp without time zone,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  metadata jsonb,
  supplier_currency text DEFAULT 'EUR'::text,
  supplier_price numeric,
  price_gbp numeric DEFAULT (supplier_price + ((supplier_price * markup_percent) / (100)::numeric)),
  ticket_days text,
  active boolean DEFAULT true,
  is_provisional boolean NOT NULL DEFAULT false,
  quantity_available integer DEFAULT 
CASE
    WHEN is_provisional THEN 0
    ELSE (quantity_total - quantity_reserved)
END,
  team_id uuid NOT NULL DEFAULT '0cef0867-1b40-4de1-9936-16b867a753d7'::uuid,
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_ticket_category_id_fkey FOREIGN KEY (ticket_category_id) REFERENCES public.ticket_categories(id),
  CONSTRAINT tickets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT tickets_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.venues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  country text,
  city text,
  timezone text,
  latitude numeric,
  longitude numeric,
  description text,
  images jsonb,
  website text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  map_img jsonb,
  CONSTRAINT venues_pkey PRIMARY KEY (id)
);
